import os 


here = os.getcwd()

def reversed(sec):
    swap = {
    "A":"T",
    "T":"A",
    "G":"C",
    "C":"G"
    }

    nu = "AGTC"

    n = []
    for i in sec:
        if i in nu:
            n.append(swap[i])
        else:
            n.append(i)
    return (''.join(n))[::-1]
def getSec(directory, reverse = None):
    try:
        with open(directory, "r") as file:
            sequence = []
            for line in file:
                if not line.startswith(">"):
                    sequence.append(line.strip())  # Adiciona a linha como string sem espaços em branco
            
           
              # Junta as strings em uma única sequência
            if not reverse:
                return ''.join(sequence)
            else:
                return reversed(''.join(sequence))
        
    except FileNotFoundError as e:
        print(e)

test = 'ATGCGTAGACACACACATCCTTACTCTGCGCGCATCCCTGGCCTGGTGGACGGAAGATCGAGCGCTCTGGGTGGACTTACGGCCACAGGACGGGGGCAGAGTCGGCAGGGAGGCCCCTCCGAGGCCCAGTGGGCCCTGCGCTGGCCCCGGCCGCAGACGCCCACCTGCTGCTGTGCTGGCTGCGGCCGCCGCCTGCTGGCCACAGAGAGCCCACGTGCGCCGGCCGCCAGGCCTGGGCATCTCCCCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCACCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCTGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCACCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCTGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGTGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCACCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCTGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGTGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCTGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGCGCCGGCCGCCAGGCCTGGGCATCTCCTCTCCTGCAGCGCCGCCTGCTGGCCACAGAGAACCCGCGTGTGCCGGCCGCCAGGCCTGGGCATCTCCCCGGGCCCTAGTTCCCCCCCTCACCTAAGGGGAGGGACTCCCGTCTTTCCATCCACCCCCTCCTTGCCTCTGCAGAGCTCCAGGGAAGGCTGGCACCCGCTCACTGCATTTAGACTCCATCAGGTTCAGACAGTGGGTCAGGGTACAAGGCTTCAGCGGCCAGGGATGTGGCCTCTAATTTGTAGAGAGAAAGAAGGACAGAGGCAAAGGTTTGGGCCCAGGGACTGGGCTCCGTTTCCAGAATCACTCTTGGAGCTGCTCTGCTGCCCCCTGCCCCATACACGTGATGGAGCAGAAAACGTGCTGTGTGAACCTGTGACTTCAGGGCCTGTTGACGTGGTCGTGCTTGCATACTCTCTGGACTGGACCTCACTGTGGGAACAACAAGATCAACAAGAGGAGCAAGAACAACATCAAGAGTCAGGGCCCGGGGGTCCTGACGGGTACAGGATGGGTACAGACCCACACAGGAATCCCAGAGTGTGTTCCACAGCAGGACACGCCTGCGCTGAAAGAGTGGGCAGAAAGGAGCTGACCTGGACCAAACCAATGCACAACTCCTACGTACTGATGGTGGTCTTACGTTTCCCTAAGTTTCTGCCGACTAAACTGTGCACACGTTCTCAGGACCTCCTGAAGCTGCGTCACAGGCGCTGA'

coordenada  = 'c611297-611112'
coordenada = [611112, 611297]
segmentPath = os.path.join(here, "chromosome1HomoSapien/CDS32.fasta")
sequencePath = os.path.join(here, "chromosome1HomoSapien/sequence.fasta")
segment = getSec(segmentPath)
sequence = getSec(sequencePath, True)

test = test[::-1]
test = test[coordenada[0]:coordenada[1]]
test = test[::-1]
try:
    if test in sequence:
        print("yes")
    else:
        print("No")
except Exception as e:
    print(type(segment))
    print(type(sequence))
    print(e)